baseURL = 'https://anime-api-2r3soktbma-uc.a.run.app/'
languageCode = 'es-es'
title = ' Anime Collection Manager'

[markup.goldmark.renderer]
  unsafe = true

[params]
  # Configuraci贸n b谩sica del tema Terminal
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  
  # Colores y tema
  themeColor = "red"
  backgroundColor = "dark"
  
  # Caracter铆sticas adicionales
  showReadingTime = true
  showShareButtons = true
  showLastUpdated = true
  showToc = true
  
  # Favicon
  favicon = "/favicon.svg"
  
  # Configuraci贸n del logo
  [params.logo]
    logoText = " Anime Collection Manager"
    logoHomeLink = "/"
    
  # Configuraci贸n de social media
  [params.social]
    github = "https://github.com/victoMR"
    
  # Configuraci贸n de la p谩gina de inicio
  [params.portrait]
    path = ""
    alt = "Anime Collection Manager"
    maxWidth = "300px"

# Men煤 de navegaci贸n
[[menu.main]]
  identifier = "home"
  name = " Inicio"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "app"
  name = " Aplicaci贸n"
  url = "/posts/anime-crud/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = " Posts"
  url = "/posts/"
  weight = 3

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'